### ISSUE TITLE
Out of date app_version in Networking package

### ISSUE THREAD

**Issue by felixspeed** [MoneyBox/iOS-Tech-Task#8]
Networking package in Networking/Sources/Networking/Base/API.swift has app_version within headers set to "8.10.0" which returns the following LoginResponse
``
The response is :  {"Name":"Moneybox version expired","Message":"This version of our app is no longer supported. Please update to the latest version in the App Store.","ValidationErrors":[]}
``

Updating this value to match the app store version of "10.33.0" returns the correct LoginResponse
``
The response is :  {"User":{"UserId":"c634381a-7f93-43ff-a21d-cb4506ee5c17","HasVerifiedEmail":true,"IsPinSet":true,"AmlStatus":"Clear","AmlAttempts":1,"KycStatus":"UpToDate","RoundUpMode":"Off","JisaRoundUpMode":"Off"...........
``

Many Thanks,
Felix

**Comment by valerio-bettini** [comment]
Thank you @felixspeed . this is now sorted.
